// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwzvcncixqsdcijvtuoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53enZjbmNpeHFzZGNpanZ0dW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Nzg1NDUsImV4cCI6MjA2MDE1NDU0NX0.HILCDdkqHP0sYYoVVzprl6h8iDhOcF-PWOJdzX4pPXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);